FROM node:18.17.1-alpine AS build

WORKDIR /app

COPY  NoteApp/package*.json ./
RUN npm install
RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
COPY NoteApp .
RUN npm run build

FROM nginx
COPY NoteApp/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/note-app/browser /usr/share/nginx/html
EXPOSE 80
