version: "3.8"

services:
  noteapp-mysql:
    container_name: noteapp-mysql
    image: krywion/noteapp-mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
    networks:
        - my-network
  noteapp-server:
    container_name: noteapp-server
    image: krywion/noteapp-server:latest
    depends_on:
      - noteapp-mysql
    restart: no
    env_file:
      - .env
    ports:
      - 8080:8080
    environment:
      - SPRING_APPLICATION_NAME=NotesAppApi
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://noteapp-mysql:3306/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_PASSWORD
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_DATABASE=mysql
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=$MAIL_USERNAME
      - SPRING_MAIL_PASSWORD=$MAIL_PASSWORD
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - API_BASE_PATH=$API_BASE_PATH
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
        - my-network
  noteapp-client:
    container_name: noteapp-client
    image: krywion/noteapp-client:latest
    ports:
      - 4200:80
    depends_on:
      - noteapp-server
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
