services:
  noteApp:
    container_name: noteapp
    build: .
    image: noteapp:v1
    ports:
      - 4200:80
    expose:
      - 80
    networks:
      - internalnet

networks:
    internalnet:
        driver: bridge

