services:
  noteApp:
    container_name: noteApp
    build: .
    image: noteapp:v1
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - internalnet

networks:
    internalnet:
        driver: bridge

