FROM maven:3.9.6 AS build

WORKDIR /app
COPY NotesAppServer/pom.xml /app
RUN mvn dependency:resolve
COPY NotesAppServer /app
RUN mvn clean
RUN mvn package -DskipTests -X

FROM openjdk
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]

